export const MY_LOAN_PAGE_STATE = 'myLoan'
export const PAYMENT_PLAN_PAGE_STATE = 'paymentPlan'
export const REFINANCE_PAGE_STATE = 'refinance'
export const MY_PROFILE_PAGE_STATE = 'myProfile'
export const LOGOUT_PAGE_STATE = 'logout'